codecov:
  require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 1%
    patch:
      default:
        target: 0%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default

