name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv (fast installer)
        uses: astral-sh/setup-uv@v4

      - name: Create virtual environment (uv)
        run: uv venv .venv

      - name: Install dependencies (uv)
        run: |
          uv pip install -p .venv/bin/python -e '.[dev]'

      - name: Lint (ruff)
        run: uv run -p .venv/bin/python ruff check .

      - name: Format check (black)
        run: uv run -p .venv/bin/python black --check .

      - name: Type check (mypy)
        run: uv run -p .venv/bin/python mypy src/cbclean

      - name: Tests with coverage
        run: uv run -p .venv/bin/python pytest --cov=cbclean --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV }}
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
